server {
    listen 80;
    listen [::]:80;
    server_name summerwork.ilelezhan.cn;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/summerwork-acme;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name summerwork-api.ilelezhan.cn;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/summerwork-acme;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
