do $$
begin
  create type public.workflow_stage as enum (
    'unscheduled', 'ready', 'in_progress', 'awaiting_review',
    'awaiting_correction', 'awaiting_redo', 'awaiting_acceptance', 'closed_loop'
  );
exception when duplicate_object then null;
end $$;

create table if not exists public.plan_dependencies (
  predecessor_task_id uuid not null references public.homework_tasks(id) on delete cascade,
  successor_task_id uuid not null references public.homework_tasks(id) on delete cascade,
  dependency_type text not null default 'finish_to_start' check (dependency_type in ('finish_to_start', 'review_after_attempt', 'correction_after_review', 'redo_after_correction', 'submission_after_review')),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  primary key(predecessor_task_id, successor_task_id),
  check (predecessor_task_id <> successor_task_id)
);

create table if not exists public.task_workflow_current (
  task_id uuid primary key references public.homework_tasks(id) on delete cascade,
  stage public.workflow_stage not null default 'ready',
  actual_seconds integer not null default 0 check (actual_seconds >= 0),
  active_started_at timestamptz,
  last_completed_at timestamptz,
  version integer not null default 1 check (version > 0),
  updated_by uuid references public.profiles(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.study_session_events (
  id bigint generated by default as identity primary key,
  task_id uuid not null references public.homework_tasks(id) on delete cascade,
  student_id uuid not null references public.students(id) on delete cascade,
  event_type text not null check (event_type in ('started', 'paused', 'resumed', 'completed', 'reopened')),
  unknown_numbers text[] not null default '{}',
  elapsed_seconds integer not null default 0 check (elapsed_seconds >= 0),
  payload jsonb not null default '{}'::jsonb,
  actor_id uuid not null references public.profiles(id),
  idempotency_key uuid not null,
  occurred_at timestamptz not null default now(),
  unique(actor_id, idempotency_key)
);

create table if not exists public.task_review_records (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.homework_tasks(id) on delete cascade,
  homework_version_id uuid not null references public.homework_versions(id) on delete restrict,
  review_number integer not null check (review_number > 0),
  accuracy_band text not null check (accuracy_band in ('100', '90+', '70-89', 'below-70')),
  wrong_numbers text[] not null default '{}',
  error_tags text[] not null default '{}',
  correction_required boolean not null,
  redo_required boolean not null,
  note text not null default '',
  reviewed_by uuid not null references public.profiles(id),
  reviewed_at timestamptz not null default now(),
  idempotency_key uuid not null,
  unique(reviewed_by, idempotency_key),
  unique(task_id, review_number),
  check (correction_required or cardinality(wrong_numbers) = 0),
  check (not redo_required or correction_required)
);

create table if not exists public.task_review_revocations (
  review_id uuid primary key references public.task_review_records(id) on delete cascade,
  reason text not null check (nullif(trim(reason), '') is not null),
  revoked_by uuid not null references public.profiles(id),
  idempotency_key uuid not null,
  revoked_at timestamptz not null default now(),
  unique(revoked_by, idempotency_key)
);

create table if not exists public.correction_attempts (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.homework_tasks(id) on delete cascade,
  review_id uuid not null references public.task_review_records(id) on delete cascade,
  attempt_number integer not null check (attempt_number > 0),
  correction_passed boolean not null,
  redo_required boolean not null,
  redo_passed boolean not null default false,
  note text not null default '',
  validated_by uuid not null references public.profiles(id),
  validated_at timestamptz not null default now(),
  idempotency_key uuid not null,
  unique(validated_by, idempotency_key),
  unique(review_id, attempt_number),
  check (not redo_passed or (correction_passed and redo_required))
);

create table if not exists public.correction_attempt_revocations (
  correction_attempt_id uuid primary key references public.correction_attempts(id) on delete cascade,
  reason text not null check (nullif(trim(reason), '') is not null),
  revoked_by uuid not null references public.profiles(id),
  idempotency_key uuid not null,
  revoked_at timestamptz not null default now(),
  unique(revoked_by, idempotency_key)
);

create table if not exists public.mastery_evidence (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students(id) on delete cascade,
  subject_id text not null references public.subjects(id),
  knowledge_node_id uuid not null references public.knowledge_nodes(id) on delete restrict,
  task_id uuid not null references public.homework_tasks(id) on delete cascade,
  homework_version_id uuid not null references public.homework_versions(id) on delete restrict,
  review_id uuid references public.task_review_records(id) on delete set null,
  correction_attempt_id uuid references public.correction_attempts(id) on delete set null,
  evidence_type text not null check (evidence_type in ('first_attempt', 'wrong_answer', 'correction', 'independent_redo', 'tutor_assessment', 'reopen')),
  level public.mastery_level not null,
  detail jsonb not null default '{}'::jsonb,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.mastery_evidence_revocations (
  evidence_id uuid primary key references public.mastery_evidence(id) on delete cascade,
  reason text not null check (nullif(trim(reason), '') is not null),
  revoked_by uuid not null references public.profiles(id),
  revoked_at timestamptz not null default now()
);

create table if not exists public.mastery_snapshots (
  student_id uuid not null references public.students(id) on delete cascade,
  knowledge_node_id uuid not null references public.knowledge_nodes(id) on delete cascade,
  subject_id text not null references public.subjects(id),
  current_level public.mastery_level not null default 'unpracticed',
  highest_level public.mastery_level not null default 'unpracticed',
  current_evidence_id uuid references public.mastery_evidence(id) on delete set null,
  latest_evidence_at timestamptz,
  highest_achieved_at timestamptz,
  version integer not null default 1 check (version > 0),
  updated_at timestamptz not null default now(),
  primary key(student_id, knowledge_node_id)
);

create table if not exists public.submission_confirmations (
  id bigint generated by default as identity primary key,
  checkpoint_id uuid not null references public.submission_checkpoints(id) on delete cascade,
  action text not null check (action in ('confirmed', 'revoked')),
  note text not null default '',
  reason text not null default '',
  actor_id uuid not null references public.profiles(id),
  idempotency_key uuid not null,
  created_at timestamptz not null default now(),
  unique(actor_id, idempotency_key),
  check (action <> 'revoked' or nullif(trim(reason), '') is not null)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  family_id uuid not null references public.family_spaces(id) on delete cascade,
  student_id uuid references public.students(id) on delete cascade,
  subject_id text references public.subjects(id),
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  notification_type text not null,
  title text not null,
  body text not null default '',
  entity_type text not null default '',
  entity_id text not null default '',
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists plan_dependencies_successor_idx on public.plan_dependencies(successor_task_id);
create index if not exists study_session_events_task_time_idx on public.study_session_events(task_id, occurred_at);
create index if not exists task_review_records_task_idx on public.task_review_records(task_id, reviewed_at desc);
create index if not exists correction_attempts_review_idx on public.correction_attempts(review_id, attempt_number desc);
create index if not exists mastery_evidence_node_time_idx on public.mastery_evidence(knowledge_node_id, created_at desc);
create index if not exists submission_confirmations_checkpoint_idx on public.submission_confirmations(checkpoint_id, created_at desc);
create index if not exists notifications_recipient_unread_idx on public.notifications(recipient_id, created_at desc) where read_at is null;

create or replace function public.is_task_tutor(target_task_id uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.homework_tasks task
    where task.id = target_task_id and task.deleted_at is null
      and public.is_subject_tutor(task.student_id, task.subject_id)
  );
$$;

create or replace function public.is_checkpoint_tutor(target_checkpoint_id uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from public.submission_checkpoints checkpoint
    join public.homeworks homework on homework.id = checkpoint.homework_id
    where checkpoint.id = target_checkpoint_id and homework.deleted_at is null
      and public.is_subject_tutor(homework.student_id, homework.subject_id)
  );
$$;

create or replace function public.initialize_task_workflow()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.task_workflow_current(task_id, stage, updated_by)
  values(new.id, 'ready', new.created_by)
  on conflict (task_id) do nothing;
  return new;
end;
$$;

drop trigger if exists homework_tasks_initialize_workflow on public.homework_tasks;
create trigger homework_tasks_initialize_workflow
after insert on public.homework_tasks
for each row execute function public.initialize_task_workflow();

insert into public.task_workflow_current(task_id, stage, updated_by)
select id, 'ready', coalesce(updated_by, created_by)
from public.homework_tasks
on conflict (task_id) do nothing;

create or replace function public.notify_task_audience(
  target_task_id uuid,
  target_audience text,
  target_type text,
  target_title text,
  target_body text default ''
)
returns void
language plpgsql security definer set search_path = public
as $$
declare task_row public.homework_tasks%rowtype;
begin
  select * into task_row from public.homework_tasks where id = target_task_id;
  if task_row.id is null then return; end if;

  if target_audience = 'parent' then
    insert into public.notifications(family_id, student_id, subject_id, recipient_id, notification_type, title, body, entity_type, entity_id)
    select task_row.family_id, task_row.student_id, task_row.subject_id, membership.user_id,
      target_type, target_title, coalesce(target_body, ''), 'task', task_row.id::text
    from public.family_memberships membership
    where membership.family_id = task_row.family_id and membership.role = 'parent' and membership.removed_at is null;
  elsif target_audience = 'tutor' then
    insert into public.notifications(family_id, student_id, subject_id, recipient_id, notification_type, title, body, entity_type, entity_id)
    select task_row.family_id, task_row.student_id, task_row.subject_id, assignment.tutor_user_id,
      target_type, target_title, coalesce(target_body, ''), 'task', task_row.id::text
    from public.tutor_assignments assignment
    where assignment.student_id = task_row.student_id and assignment.subject_id = task_row.subject_id
      and assignment.starts_at <= now() and (assignment.ends_at is null or assignment.ends_at > now());
  elsif target_audience = 'student' then
    insert into public.notifications(family_id, student_id, subject_id, recipient_id, notification_type, title, body, entity_type, entity_id)
    select task_row.family_id, task_row.student_id, task_row.subject_id, student.user_id,
      target_type, target_title, coalesce(target_body, ''), 'task', task_row.id::text
    from public.students student
    where student.id = task_row.student_id and student.user_id is not null;
  end if;
end;
$$;

create or replace function public.recalculate_mastery_snapshot(target_knowledge_node_id uuid)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  node_row public.knowledge_nodes%rowtype;
  current_evidence public.mastery_evidence%rowtype;
  highest_evidence public.mastery_evidence%rowtype;
begin
  select * into node_row from public.knowledge_nodes where id = target_knowledge_node_id;
  if node_row.id is null then return; end if;

  select evidence.* into current_evidence
  from public.mastery_evidence evidence
  where evidence.knowledge_node_id = target_knowledge_node_id
    and not exists (
      select 1 from public.mastery_evidence_revocations revocation
      where revocation.evidence_id = evidence.id
    )
  order by evidence.created_at desc, evidence.id desc
  limit 1;

  select evidence.* into highest_evidence
  from public.mastery_evidence evidence
  where evidence.knowledge_node_id = target_knowledge_node_id
    and not exists (
      select 1 from public.mastery_evidence_revocations revocation
      where revocation.evidence_id = evidence.id
    )
  order by case evidence.level
      when 'mastered' then 4
      when 'basic' then 3
      when 'practiced' then 2
      when 'reinforce' then 1
      else 0 end desc,
    evidence.created_at desc, evidence.id desc
  limit 1;

  insert into public.mastery_snapshots(
    student_id, knowledge_node_id, subject_id, current_level, highest_level,
    current_evidence_id, latest_evidence_at, highest_achieved_at
  ) values (
    node_row.student_id, node_row.id, node_row.subject_id,
    coalesce(current_evidence.level, 'unpracticed'::public.mastery_level),
    coalesce(highest_evidence.level, 'unpracticed'::public.mastery_level),
    current_evidence.id, current_evidence.created_at, highest_evidence.created_at
  )
  on conflict (student_id, knowledge_node_id) do update set
    current_level = excluded.current_level,
    highest_level = excluded.highest_level,
    current_evidence_id = excluded.current_evidence_id,
    latest_evidence_at = excluded.latest_evidence_at,
    highest_achieved_at = excluded.highest_achieved_at,
    version = public.mastery_snapshots.version + 1,
    updated_at = now();
end;
$$;

create or replace function public.refresh_task_workflow(target_task_id uuid)
returns public.workflow_stage
language plpgsql security definer set search_path = public
as $$
declare
  task_row public.homework_tasks%rowtype;
  activity_row public.student_task_activity%rowtype;
  review_row public.task_review_records%rowtype;
  correction_row public.correction_attempts%rowtype;
  next_stage public.workflow_stage;
  has_mastery boolean;
  submissions_complete boolean;
begin
  select * into task_row from public.homework_tasks where id = target_task_id;
  if task_row.id is null then raise exception 'task not found'; end if;

  select * into activity_row from public.student_task_activity where task_id = target_task_id;
  if activity_row.task_id is null or activity_row.run_state = 'ready' then
    next_stage := 'ready';
  elsif activity_row.run_state in ('running', 'paused') then
    next_stage := 'in_progress';
  else
    select review.* into review_row
    from public.task_review_records review
    where review.task_id = target_task_id
      and not exists (select 1 from public.task_review_revocations revoked where revoked.review_id = review.id)
    order by review.review_number desc limit 1;

    if review_row.id is null then
      next_stage := 'awaiting_review';
    else
      select correction.* into correction_row
      from public.correction_attempts correction
      where correction.review_id = review_row.id
        and not exists (
          select 1 from public.correction_attempt_revocations revoked
          where revoked.correction_attempt_id = correction.id
        )
      order by correction.attempt_number desc limit 1;

      if review_row.correction_required and (correction_row.id is null or not correction_row.correction_passed) then
        next_stage := 'awaiting_correction';
      elsif review_row.redo_required and (correction_row.id is null or not correction_row.redo_passed) then
        next_stage := 'awaiting_redo';
      else
        select exists (
          select 1 from public.task_knowledge_links link
          where link.task_id = target_task_id
        ) and not exists (
          select 1 from public.task_knowledge_links link
          where link.task_id = target_task_id
            and not exists (
              select 1 from public.mastery_evidence evidence
              where evidence.task_id = target_task_id
                and evidence.knowledge_node_id = link.knowledge_node_id
                and evidence.evidence_type = 'tutor_assessment'
                and evidence.level = 'mastered'
                and not exists (
                  select 1 from public.mastery_evidence_revocations revoked
                  where revoked.evidence_id = evidence.id
                )
            )
        ) into has_mastery;

        if not has_mastery then
          next_stage := 'awaiting_acceptance';
        else
          select not exists (
            select 1 from public.submission_checkpoints checkpoint
            where checkpoint.homework_id = task_row.homework_id and checkpoint.required
              and checkpoint.status <> 'confirmed'
          ) into submissions_complete;
          next_stage := case when submissions_complete then 'closed_loop' else 'awaiting_acceptance' end;
        end if;
      end if;
    end if;
  end if;

  insert into public.task_workflow_current(task_id, stage, updated_by)
  values(target_task_id, next_stage, auth.uid())
  on conflict (task_id) do update set
    stage = excluded.stage,
    version = public.task_workflow_current.version + 1,
    updated_by = coalesce(auth.uid(), public.task_workflow_current.updated_by),
    updated_at = now();
  return next_stage;
end;
$$;

create or replace function public.record_student_task_event(
  target_task_id uuid,
  target_event text,
  target_unknown_numbers text[],
  expected_version integer,
  target_idempotency_key uuid
)
returns public.task_workflow_current
language plpgsql security definer set search_path = public
as $$
declare
  task_row public.homework_tasks%rowtype;
  workflow_row public.task_workflow_current%rowtype;
  elapsed integer := 0;
  normalized_unknowns text[] := '{}';
  logged_event text;
  node_id uuid;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if target_idempotency_key is null then raise exception 'idempotency key required'; end if;
  if target_event not in ('started', 'paused', 'completed') then raise exception 'invalid student event'; end if;

  if exists (
    select 1 from public.study_session_events
    where actor_id = auth.uid() and idempotency_key = target_idempotency_key
  ) then
    select * into workflow_row from public.task_workflow_current where task_id = target_task_id;
    return workflow_row;
  end if;

  select * into task_row from public.homework_tasks where id = target_task_id and deleted_at is null;
  if task_row.id is null or not public.is_student_owner(task_row.student_id) then raise exception 'student access required'; end if;
  select * into workflow_row from public.task_workflow_current where task_id = target_task_id for update;
  if workflow_row.task_id is null then raise exception 'workflow not initialized'; end if;
  if workflow_row.version <> expected_version then raise exception 'version conflict'; end if;

  select coalesce(array_agg(value order by ordinal), '{}') into normalized_unknowns
  from (
    select trim(raw_value) value, min(ordinal) ordinal
    from unnest(coalesce(target_unknown_numbers, '{}')) with ordinality input(raw_value, ordinal)
    where nullif(trim(raw_value), '') is not null
    group by trim(raw_value)
  ) normalized;

  if target_event = 'started' then
    if workflow_row.stage not in ('ready', 'in_progress') then raise exception 'task cannot be started from current stage'; end if;
    if workflow_row.active_started_at is not null then raise exception 'task already running'; end if;
    logged_event := case when workflow_row.stage = 'in_progress' then 'resumed' else 'started' end;
    update public.task_workflow_current set active_started_at = now() where task_id = target_task_id;
    insert into public.student_task_activity(task_id, student_id, run_state, unknown_numbers, started_at)
    values(target_task_id, task_row.student_id, 'running', normalized_unknowns, now())
    on conflict (task_id) do update set
      run_state = 'running', unknown_numbers = excluded.unknown_numbers,
      started_at = coalesce(public.student_task_activity.started_at, excluded.started_at), updated_at = now();
  elsif target_event = 'paused' then
    if workflow_row.stage <> 'in_progress' or workflow_row.active_started_at is null then raise exception 'task is not running'; end if;
    elapsed := greatest(0, floor(extract(epoch from (now() - workflow_row.active_started_at)))::integer);
    logged_event := 'paused';
    update public.task_workflow_current
    set actual_seconds = actual_seconds + elapsed, active_started_at = null
    where task_id = target_task_id;
    update public.student_task_activity
    set run_state = 'paused', unknown_numbers = normalized_unknowns, updated_at = now()
    where task_id = target_task_id;
  else
    if workflow_row.stage <> 'in_progress' then raise exception 'task is not in progress'; end if;
    if workflow_row.active_started_at is not null then
      elapsed := greatest(0, floor(extract(epoch from (now() - workflow_row.active_started_at)))::integer);
    end if;
    logged_event := 'completed';
    update public.task_workflow_current
    set actual_seconds = actual_seconds + elapsed, active_started_at = null, last_completed_at = now()
    where task_id = target_task_id;
    update public.student_task_activity
    set run_state = 'completed', unknown_numbers = normalized_unknowns,
      completed_at = now(), updated_at = now()
    where task_id = target_task_id;

    for node_id in
      select link.knowledge_node_id
      from public.task_knowledge_links link
      where link.task_id = task_row.id
    loop
      insert into public.mastery_evidence(
        student_id, subject_id, knowledge_node_id, task_id, homework_version_id,
        evidence_type, level, detail, created_by
      ) values (
        task_row.student_id, task_row.subject_id, node_id, task_row.id,
        task_row.homework_version_id, 'first_attempt', 'practiced',
        jsonb_build_object('unknown_numbers', normalized_unknowns), auth.uid()
      );
      perform public.recalculate_mastery_snapshot(node_id);
    end loop;
  end if;

  insert into public.study_session_events(
    task_id, student_id, event_type, unknown_numbers, elapsed_seconds,
    actor_id, idempotency_key
  ) values (
    target_task_id, task_row.student_id, logged_event, normalized_unknowns,
    elapsed, auth.uid(), target_idempotency_key
  );

  perform public.refresh_task_workflow(target_task_id);
  insert into public.change_events(
    family_id, student_id, subject_id, entity_type, entity_id, event_type,
    after_value, actor_id, idempotency_key
  ) values (
    task_row.family_id, task_row.student_id, task_row.subject_id, 'task',
    task_row.id::text, 'student_' || logged_event,
    jsonb_build_object('unknown_numbers', normalized_unknowns, 'elapsed_seconds', elapsed),
    auth.uid(), target_idempotency_key
  );
  if logged_event = 'completed' then
    perform public.notify_task_audience(target_task_id, 'tutor', 'task_awaiting_review', '孩子已完成，等待批改', task_row.title);
  end if;
  select * into workflow_row from public.task_workflow_current where task_id = target_task_id;
  return workflow_row;
end;
$$;

create or replace function public.move_homework_blocks(
  target_task_id uuid,
  target_date date,
  change_reason text,
  expected_version integer,
  move_following boolean,
  target_idempotency_key uuid
)
returns integer
language plpgsql security definer set search_path = public
as $$
declare
  root_task public.homework_tasks%rowtype;
  affected_id uuid;
  affected_old_date date;
  date_delta integer;
  moved_count integer := 0;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if target_date is null then raise exception 'target date required'; end if;
  if nullif(trim(change_reason), '') is null then raise exception 'change reason required'; end if;
  if target_idempotency_key is null then raise exception 'idempotency key required'; end if;
  if exists (select 1 from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key) then
    select coalesce((after_value ->> 'moved_count')::integer, 0) into moved_count
    from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key;
    return moved_count;
  end if;

  select * into root_task from public.homework_tasks where id = target_task_id and deleted_at is null for update;
  if root_task.id is null or not public.is_task_tutor(root_task.id) then raise exception 'subject tutor access required'; end if;
  if root_task.version <> expected_version then raise exception 'version conflict'; end if;
  date_delta := target_date - root_task.planned_date;
  if date_delta = 0 then return 0; end if;

  for affected_id, affected_old_date in
    with recursive affected(task_id) as (
      select root_task.id
      union
      select dependency.successor_task_id
      from public.plan_dependencies dependency
      join affected on affected.task_id = dependency.predecessor_task_id
      join public.homework_tasks successor on successor.id = dependency.successor_task_id
      where move_following and successor.deleted_at is null
        and successor.student_id = root_task.student_id and successor.subject_id = root_task.subject_id
    )
    select task.id, task.planned_date
    from affected join public.homework_tasks task on task.id = affected.task_id
    order by task.sequence_number, task.id
  loop
    update public.homework_tasks
    set planned_date = affected_old_date + date_delta,
      version = version + 1, updated_by = auth.uid()
    where id = affected_id;
    insert into public.task_plan_changes(task_id, old_date, new_date, reason, changed_by)
    values(affected_id, affected_old_date, affected_old_date + date_delta, trim(change_reason), auth.uid());
    moved_count := moved_count + 1;
  end loop;

  insert into public.change_events(
    family_id, student_id, subject_id, entity_type, entity_id, event_type,
    before_value, after_value, reason, actor_id, idempotency_key
  ) values (
    root_task.family_id, root_task.student_id, root_task.subject_id, 'task',
    root_task.id::text, case when move_following then 'plan_chain_moved' else 'plan_block_moved' end,
    jsonb_build_object('planned_date', root_task.planned_date),
    jsonb_build_object('planned_date', target_date, 'moved_count', moved_count),
    trim(change_reason), auth.uid(), target_idempotency_key
  );
  perform public.notify_task_audience(root_task.id, 'parent', 'plan_changed', '家教已调整本科计划', trim(change_reason));
  return moved_count;
end;
$$;

create or replace function public.append_homework_block(
  target_homework_id uuid,
  target_date date,
  target_block_type public.plan_block_type,
  change_reason text,
  target_idempotency_key uuid
)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  homework_row public.homeworks%rowtype;
  source_task public.homework_tasks%rowtype;
  new_task_id uuid;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if target_date is null then raise exception 'target date required'; end if;
  if nullif(trim(change_reason), '') is null then raise exception 'change reason required'; end if;
  if target_idempotency_key is null then raise exception 'idempotency key required'; end if;
  if exists (select 1 from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key) then
    select (after_value ->> 'task_id')::uuid into new_task_id
    from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key;
    return new_task_id;
  end if;

  select * into homework_row from public.homeworks where id = target_homework_id and status = 'active' and deleted_at is null;
  if homework_row.id is null or not public.is_subject_tutor(homework_row.student_id, homework_row.subject_id) then raise exception 'subject tutor access required'; end if;
  select * into source_task from public.homework_tasks
  where homework_id = target_homework_id and deleted_at is null
  order by sequence_number desc, created_at desc limit 1;
  if source_task.id is null then raise exception 'source block not found'; end if;

  insert into public.homework_tasks(
    family_id, student_id, catalog_id, template_id, homework_id, homework_version_id,
    subject_id, title, planned_date, original_date, slot_type, knowledge, knowledge_tags,
    answer_basis, submission_requirement, notes, task_kind, block_minutes,
    recommended_minutes, requires_submission, course_integrated, optional, uncertainty,
    priority, answer_policy, requirement_level, evidence_required, source_reference,
    deadline_date, deadline_at, deadline_precision, block_type, sequence_number,
    created_by, updated_by
  ) values (
    source_task.family_id, source_task.student_id, source_task.catalog_id, null,
    source_task.homework_id, homework_row.current_version_id, source_task.subject_id,
    source_task.title, target_date, target_date, 'tutor_added', source_task.knowledge,
    source_task.knowledge_tags, source_task.answer_basis, source_task.submission_requirement,
    source_task.notes, source_task.task_kind, 90, 90, source_task.requires_submission,
    source_task.course_integrated, source_task.optional, source_task.uncertainty,
    source_task.priority, source_task.answer_policy, source_task.requirement_level,
    source_task.evidence_required, source_task.source_reference, source_task.deadline_date,
    source_task.deadline_at, source_task.deadline_precision, target_block_type,
    source_task.sequence_number + 1, auth.uid(), auth.uid()
  ) returning id into new_task_id;

  insert into public.plan_dependencies(predecessor_task_id, successor_task_id, dependency_type, created_by)
  values(source_task.id, new_task_id,
    case target_block_type
      when 'tutor_review' then 'review_after_attempt'
      when 'correction' then 'correction_after_review'
      when 'independent_redo' then 'redo_after_correction'
      when 'submission_confirmation' then 'submission_after_review'
      else 'finish_to_start' end,
    auth.uid());

  insert into public.change_events(
    family_id, student_id, subject_id, entity_type, entity_id, event_type,
    after_value, reason, actor_id, idempotency_key
  ) values (
    homework_row.family_id, homework_row.student_id, homework_row.subject_id,
    'task', new_task_id::text, 'plan_block_appended',
    jsonb_build_object('task_id', new_task_id, 'planned_date', target_date, 'block_type', target_block_type),
    trim(change_reason), auth.uid(), target_idempotency_key
  );
  perform public.notify_task_audience(new_task_id, 'parent', 'plan_changed', '家教已追加任务块', trim(change_reason));
  return new_task_id;
end;
$$;

create or replace function public.split_homework_block(
  target_task_id uuid,
  first_block_minutes integer,
  second_block_date date,
  change_reason text,
  expected_version integer,
  target_idempotency_key uuid
)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  task_row public.homework_tasks%rowtype;
  workflow_row public.task_workflow_current%rowtype;
  second_task_id uuid;
  second_minutes integer;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if second_block_date is null then raise exception 'second block date required'; end if;
  if nullif(trim(change_reason), '') is null then raise exception 'change reason required'; end if;
  if target_idempotency_key is null then raise exception 'idempotency key required'; end if;
  if exists (select 1 from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key) then
    select (after_value ->> 'second_task_id')::uuid into second_task_id
    from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key;
    return second_task_id;
  end if;

  select * into task_row from public.homework_tasks where id = target_task_id and deleted_at is null for update;
  if task_row.id is null or not public.is_task_tutor(task_row.id) then raise exception 'subject tutor access required'; end if;
  if task_row.version <> expected_version then raise exception 'version conflict'; end if;
  select * into workflow_row from public.task_workflow_current where task_id = target_task_id for update;
  if workflow_row.stage <> 'ready' or exists (select 1 from public.study_session_events where task_id = target_task_id) then raise exception 'only unstarted block can be split'; end if;
  if first_block_minutes < 15 or first_block_minutes > task_row.block_minutes - 15 then raise exception 'split minutes out of range'; end if;
  second_minutes := task_row.block_minutes - first_block_minutes;

  update public.homework_tasks
  set sequence_number = sequence_number + 1, version = version + 1, updated_by = auth.uid()
  where homework_id = task_row.homework_id and sequence_number > task_row.sequence_number and deleted_at is null;
  update public.homework_tasks
  set block_minutes = first_block_minutes, recommended_minutes = first_block_minutes,
    version = version + 1, updated_by = auth.uid()
  where id = task_row.id;

  insert into public.homework_tasks(
    family_id, student_id, catalog_id, template_id, homework_id, homework_version_id,
    subject_id, title, planned_date, original_date, slot_type, knowledge, knowledge_tags,
    answer_basis, submission_requirement, notes, task_kind, block_minutes,
    recommended_minutes, requires_submission, course_integrated, optional, uncertainty,
    priority, answer_policy, requirement_level, evidence_required, source_reference,
    deadline_date, deadline_at, deadline_precision, block_type, sequence_number,
    created_by, updated_by
  ) values (
    task_row.family_id, task_row.student_id, task_row.catalog_id, null,
    task_row.homework_id, task_row.homework_version_id, task_row.subject_id,
    task_row.title, second_block_date, second_block_date, 'split_continuation',
    task_row.knowledge, task_row.knowledge_tags, task_row.answer_basis,
    task_row.submission_requirement, task_row.notes, task_row.task_kind,
    second_minutes, second_minutes, task_row.requires_submission,
    task_row.course_integrated, task_row.optional, task_row.uncertainty,
    task_row.priority, task_row.answer_policy, task_row.requirement_level,
    task_row.evidence_required, task_row.source_reference, task_row.deadline_date,
    task_row.deadline_at, task_row.deadline_precision, 'continuation',
    task_row.sequence_number + 1, auth.uid(), auth.uid()
  ) returning id into second_task_id;

  update public.plan_dependencies
  set predecessor_task_id = second_task_id
  where predecessor_task_id = task_row.id;
  insert into public.plan_dependencies(predecessor_task_id, successor_task_id, dependency_type, created_by)
  values(task_row.id, second_task_id, 'finish_to_start', auth.uid());

  insert into public.change_events(
    family_id, student_id, subject_id, entity_type, entity_id, event_type,
    before_value, after_value, reason, actor_id, idempotency_key
  ) values (
    task_row.family_id, task_row.student_id, task_row.subject_id, 'task', task_row.id::text,
    'plan_block_split', jsonb_build_object('minutes', task_row.block_minutes),
    jsonb_build_object('first_minutes', first_block_minutes, 'second_minutes', second_minutes,
      'second_task_id', second_task_id, 'second_date', second_block_date),
    trim(change_reason), auth.uid(), target_idempotency_key
  );
  perform public.notify_task_audience(task_row.id, 'parent', 'plan_changed', '家教已拆分任务块', trim(change_reason));
  return second_task_id;
end;
$$;

create or replace function public.merge_homework_blocks(
  target_first_task_id uuid,
  target_second_task_id uuid,
  first_expected_version integer,
  second_expected_version integer,
  change_reason text,
  target_idempotency_key uuid
)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  first_task public.homework_tasks%rowtype;
  second_task public.homework_tasks%rowtype;
  first_workflow public.task_workflow_current%rowtype;
  second_workflow public.task_workflow_current%rowtype;
  merged_minutes integer;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if target_first_task_id = target_second_task_id then raise exception 'two distinct blocks required'; end if;
  if nullif(trim(change_reason), '') is null then raise exception 'change reason required'; end if;
  if target_idempotency_key is null then raise exception 'idempotency key required'; end if;
  if exists (select 1 from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key) then return target_first_task_id; end if;

  select * into first_task from public.homework_tasks where id = target_first_task_id and deleted_at is null for update;
  select * into second_task from public.homework_tasks where id = target_second_task_id and deleted_at is null for update;
  if first_task.id is null or second_task.id is null then raise exception 'block not found'; end if;
  if first_task.homework_id is distinct from second_task.homework_id then raise exception 'blocks must belong to one homework'; end if;
  if not public.is_task_tutor(first_task.id) or not public.is_task_tutor(second_task.id) then raise exception 'subject tutor access required'; end if;
  if first_task.version <> first_expected_version or second_task.version <> second_expected_version then raise exception 'version conflict'; end if;
  select * into first_workflow from public.task_workflow_current where task_id = first_task.id for update;
  select * into second_workflow from public.task_workflow_current where task_id = second_task.id for update;
  if first_workflow.stage <> 'ready' or second_workflow.stage <> 'ready'
    or exists (select 1 from public.study_session_events where task_id in (first_task.id, second_task.id))
  then raise exception 'only unstarted blocks can be merged'; end if;
  merged_minutes := first_task.block_minutes + second_task.block_minutes;
  if merged_minutes > 360 then raise exception 'merged duration exceeds limit'; end if;

  insert into public.plan_dependencies(predecessor_task_id, successor_task_id, dependency_type, created_by)
  select first_task.id, dependency.successor_task_id, dependency.dependency_type, auth.uid()
  from public.plan_dependencies dependency
  where dependency.predecessor_task_id = second_task.id and dependency.successor_task_id <> first_task.id
  on conflict do nothing;
  insert into public.plan_dependencies(predecessor_task_id, successor_task_id, dependency_type, created_by)
  select dependency.predecessor_task_id, first_task.id, dependency.dependency_type, auth.uid()
  from public.plan_dependencies dependency
  where dependency.successor_task_id = second_task.id and dependency.predecessor_task_id <> first_task.id
  on conflict do nothing;
  delete from public.plan_dependencies
  where predecessor_task_id = second_task.id or successor_task_id = second_task.id
    or (predecessor_task_id = first_task.id and successor_task_id = second_task.id)
    or (predecessor_task_id = second_task.id and successor_task_id = first_task.id);

  update public.homework_tasks
  set block_minutes = merged_minutes, recommended_minutes = merged_minutes,
    version = version + 1, updated_by = auth.uid()
  where id = first_task.id;
  update public.homework_tasks
  set deleted_at = now(), deleted_by = auth.uid(), version = version + 1,
    updated_by = auth.uid()
  where id = second_task.id;

  insert into public.change_events(
    family_id, student_id, subject_id, entity_type, entity_id, event_type,
    before_value, after_value, reason, actor_id, idempotency_key
  ) values (
    first_task.family_id, first_task.student_id, first_task.subject_id, 'task',
    first_task.id::text, 'plan_blocks_merged',
    jsonb_build_object('first_minutes', first_task.block_minutes, 'second_task_id', second_task.id, 'second_minutes', second_task.block_minutes),
    jsonb_build_object('task_id', first_task.id, 'minutes', merged_minutes),
    trim(change_reason), auth.uid(), target_idempotency_key
  );
  perform public.notify_task_audience(first_task.id, 'parent', 'plan_changed', '家教已合并任务块', trim(change_reason));
  return first_task.id;
end;
$$;

create or replace function public.save_task_review(
  target_task_id uuid,
  target_accuracy_band text,
  target_wrong_numbers text[],
  target_error_tags text[],
  target_correction_required boolean,
  target_redo_required boolean,
  target_note text,
  expected_version integer,
  target_idempotency_key uuid
)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  task_row public.homework_tasks%rowtype;
  workflow_row public.task_workflow_current%rowtype;
  review_id uuid;
  next_review_number integer;
  normalized_wrongs text[] := '{}';
  normalized_tags text[] := '{}';
  node_id uuid;
  evidence_level public.mastery_level;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if target_idempotency_key is null then raise exception 'idempotency key required'; end if;
  if target_accuracy_band not in ('100', '90+', '70-89', 'below-70') then raise exception 'invalid accuracy band'; end if;
  if exists (select 1 from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key) then
    select (after_value ->> 'review_id')::uuid into review_id
    from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key;
    return review_id;
  end if;

  select * into task_row from public.homework_tasks where id = target_task_id and deleted_at is null;
  if task_row.id is null or not public.is_task_tutor(task_row.id) then raise exception 'subject tutor access required'; end if;
  select * into workflow_row from public.task_workflow_current where task_id = target_task_id for update;
  if workflow_row.version <> expected_version then raise exception 'version conflict'; end if;
  if workflow_row.stage <> 'awaiting_review' then raise exception 'task is not awaiting review'; end if;

  select coalesce(array_agg(value order by ordinal), '{}') into normalized_wrongs
  from (
    select trim(raw_value) value, min(ordinal) ordinal
    from unnest(coalesce(target_wrong_numbers, '{}')) with ordinality input(raw_value, ordinal)
    where nullif(trim(raw_value), '') is not null
    group by trim(raw_value)
  ) normalized;
  select coalesce(array_agg(value order by ordinal), '{}') into normalized_tags
  from (
    select trim(raw_value) value, min(ordinal) ordinal
    from unnest(coalesce(target_error_tags, '{}')) with ordinality input(raw_value, ordinal)
    where nullif(trim(raw_value), '') is not null
    group by trim(raw_value)
  ) normalized;
  if cardinality(normalized_wrongs) > 0 and not target_correction_required then raise exception 'wrong answers require correction'; end if;
  if target_redo_required and not target_correction_required then raise exception 'redo requires correction'; end if;
  if exists (
    select 1 from public.task_review_records review
    where review.task_id = target_task_id
      and not exists (select 1 from public.task_review_revocations revoked where revoked.review_id = review.id)
  ) then raise exception 'active review already exists'; end if;

  select coalesce(max(review_number), 0) + 1 into next_review_number
  from public.task_review_records where task_id = target_task_id;
  insert into public.task_review_records(
    task_id, homework_version_id, review_number, accuracy_band, wrong_numbers,
    error_tags, correction_required, redo_required, note, reviewed_by, idempotency_key
  ) values (
    target_task_id, task_row.homework_version_id, next_review_number,
    target_accuracy_band, normalized_wrongs, normalized_tags,
    target_correction_required, target_redo_required, coalesce(target_note, ''),
    auth.uid(), target_idempotency_key
  ) returning id into review_id;

  evidence_level := case when cardinality(normalized_wrongs) > 0 then 'reinforce'::public.mastery_level else 'practiced'::public.mastery_level end;
  for node_id in
    select link.knowledge_node_id from public.task_knowledge_links link
    where link.task_id = task_row.id
  loop
    insert into public.mastery_evidence(
      student_id, subject_id, knowledge_node_id, task_id, homework_version_id,
      review_id, evidence_type, level, detail, created_by
    ) values (
      task_row.student_id, task_row.subject_id, node_id, task_row.id,
      task_row.homework_version_id, review_id,
      case when cardinality(normalized_wrongs) > 0 then 'wrong_answer' else 'tutor_assessment' end,
      evidence_level,
      jsonb_build_object('accuracy_band', target_accuracy_band, 'wrong_numbers', normalized_wrongs, 'error_tags', normalized_tags),
      auth.uid()
    );
    perform public.recalculate_mastery_snapshot(node_id);
  end loop;

  insert into public.task_reviews(
    task_id, reviewed_by, accuracy_band, wrong_numbers, error_tags,
    correction_passed, redo_required, redo_passed, mastery_confirmed,
    review_confirmed_at, review_saved_at, note
  ) values (
    target_task_id, auth.uid(), target_accuracy_band, normalized_wrongs,
    normalized_tags, false, target_redo_required, false, false, now(), now(),
    coalesce(target_note, '')
  )
  on conflict (task_id) do update set
    reviewed_by = excluded.reviewed_by, accuracy_band = excluded.accuracy_band,
    wrong_numbers = excluded.wrong_numbers, error_tags = excluded.error_tags,
    correction_passed = false, redo_required = excluded.redo_required,
    redo_passed = false, mastery_confirmed = false,
    review_confirmed_at = excluded.review_confirmed_at,
    review_saved_at = excluded.review_saved_at, note = excluded.note, updated_at = now();

  perform public.refresh_task_workflow(target_task_id);
  insert into public.change_events(
    family_id, student_id, subject_id, entity_type, entity_id, event_type,
    after_value, actor_id, idempotency_key
  ) values (
    task_row.family_id, task_row.student_id, task_row.subject_id, 'review',
    review_id::text, 'review_confirmed',
    jsonb_build_object('review_id', review_id, 'accuracy_band', target_accuracy_band,
      'wrong_count', cardinality(normalized_wrongs), 'correction_required', target_correction_required,
      'redo_required', target_redo_required),
    auth.uid(), target_idempotency_key
  );
  perform public.notify_task_audience(target_task_id, 'student',
    case when target_correction_required then 'correction_required' else 'mastery_pending' end,
    case when target_correction_required then '批改完成，请按错题订正' else '批改完成' end,
    task_row.title);
  return review_id;
end;
$$;

create or replace function public.revoke_task_review(
  target_task_id uuid,
  target_revoke_reason text,
  expected_version integer,
  target_idempotency_key uuid
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  task_row public.homework_tasks%rowtype;
  workflow_row public.task_workflow_current%rowtype;
  review_row public.task_review_records%rowtype;
  evidence_row record;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if nullif(trim(target_revoke_reason), '') is null then raise exception 'revoke reason required'; end if;
  if target_idempotency_key is null then raise exception 'idempotency key required'; end if;
  if exists (select 1 from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key) then return; end if;
  select * into task_row from public.homework_tasks where id = target_task_id and deleted_at is null;
  if task_row.id is null or not public.is_task_tutor(task_row.id) then raise exception 'subject tutor access required'; end if;
  select * into workflow_row from public.task_workflow_current where task_id = target_task_id for update;
  if workflow_row.version <> expected_version then raise exception 'version conflict'; end if;
  select review.* into review_row from public.task_review_records review
  where review.task_id = target_task_id
    and not exists (select 1 from public.task_review_revocations revoked where revoked.review_id = review.id)
  order by review.review_number desc limit 1;
  if review_row.id is null then raise exception 'active review not found'; end if;

  insert into public.task_review_revocations(review_id, reason, revoked_by, idempotency_key)
  values(review_row.id, trim(target_revoke_reason), auth.uid(), target_idempotency_key);
  for evidence_row in
    select evidence.id, evidence.knowledge_node_id from public.mastery_evidence evidence
    where evidence.review_id = review_row.id
      and not exists (select 1 from public.mastery_evidence_revocations revoked where revoked.evidence_id = evidence.id)
  loop
    insert into public.mastery_evidence_revocations(evidence_id, reason, revoked_by)
    values(evidence_row.id, trim(target_revoke_reason), auth.uid());
    perform public.recalculate_mastery_snapshot(evidence_row.knowledge_node_id);
  end loop;
  delete from public.task_reviews where task_id = target_task_id;
  perform public.refresh_task_workflow(target_task_id);
  insert into public.change_events(
    family_id, student_id, subject_id, entity_type, entity_id, event_type,
    before_value, reason, actor_id, idempotency_key
  ) values (
    task_row.family_id, task_row.student_id, task_row.subject_id, 'review',
    review_row.id::text, 'review_revoked', jsonb_build_object('review_id', review_row.id),
    trim(target_revoke_reason), auth.uid(), target_idempotency_key
  );
end;
$$;

create or replace function public.record_correction_attempt(
  target_task_id uuid,
  correction_passed boolean,
  redo_passed boolean,
  target_note text,
  expected_version integer,
  target_idempotency_key uuid
)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  task_row public.homework_tasks%rowtype;
  workflow_row public.task_workflow_current%rowtype;
  review_row public.task_review_records%rowtype;
  prior_attempt public.correction_attempts%rowtype;
  attempt_id uuid;
  next_attempt_number integer;
  node_id uuid;
  evidence_level public.mastery_level;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if target_idempotency_key is null then raise exception 'idempotency key required'; end if;
  if exists (select 1 from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key) then
    select (after_value ->> 'attempt_id')::uuid into attempt_id
    from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key;
    return attempt_id;
  end if;
  select * into task_row from public.homework_tasks where id = target_task_id and deleted_at is null;
  if task_row.id is null or not public.is_task_tutor(task_row.id) then raise exception 'subject tutor access required'; end if;
  select * into workflow_row from public.task_workflow_current where task_id = target_task_id for update;
  if workflow_row.version <> expected_version then raise exception 'version conflict'; end if;
  if workflow_row.stage not in ('awaiting_correction', 'awaiting_redo') then raise exception 'task is not awaiting correction or redo'; end if;
  select review.* into review_row from public.task_review_records review
  where review.task_id = target_task_id
    and not exists (select 1 from public.task_review_revocations revoked where revoked.review_id = review.id)
  order by review.review_number desc limit 1;
  if review_row.id is null or not review_row.correction_required then raise exception 'active correction requirement not found'; end if;
  if redo_passed and (not correction_passed or not review_row.redo_required) then raise exception 'redo result is inconsistent'; end if;
  select correction.* into prior_attempt from public.correction_attempts correction
  where correction.review_id = review_row.id
    and not exists (select 1 from public.correction_attempt_revocations revoked where revoked.correction_attempt_id = correction.id)
  order by correction.attempt_number desc limit 1;
  if prior_attempt.correction_passed and (not review_row.redo_required or prior_attempt.redo_passed) then raise exception 'correction is already accepted'; end if;
  select coalesce(max(attempt_number), 0) + 1 into next_attempt_number
  from public.correction_attempts where review_id = review_row.id;

  insert into public.correction_attempts(
    task_id, review_id, attempt_number, correction_passed, redo_required,
    redo_passed, note, validated_by, idempotency_key
  ) values (
    target_task_id, review_row.id, next_attempt_number, correction_passed,
    review_row.redo_required, redo_passed, coalesce(target_note, ''),
    auth.uid(), target_idempotency_key
  ) returning id into attempt_id;

  evidence_level := case
    when not correction_passed then 'reinforce'::public.mastery_level
    else 'basic'::public.mastery_level end;
  for node_id in
    select link.knowledge_node_id from public.task_knowledge_links link
    where link.task_id = task_row.id
  loop
    insert into public.mastery_evidence(
      student_id, subject_id, knowledge_node_id, task_id, homework_version_id,
      review_id, correction_attempt_id, evidence_type, level, detail, created_by
    ) values (
      task_row.student_id, task_row.subject_id, node_id, task_row.id,
      task_row.homework_version_id, review_row.id, attempt_id,
      case when redo_passed then 'independent_redo' else 'correction' end,
      evidence_level,
      jsonb_build_object('attempt_number', next_attempt_number, 'correction_passed', correction_passed, 'redo_passed', redo_passed),
      auth.uid()
    );
    perform public.recalculate_mastery_snapshot(node_id);
  end loop;

  update public.task_reviews
  set correction_passed = record_correction_attempt.correction_passed,
    redo_passed = record_correction_attempt.redo_passed, updated_at = now()
  where task_id = target_task_id;
  perform public.refresh_task_workflow(target_task_id);
  insert into public.change_events(
    family_id, student_id, subject_id, entity_type, entity_id, event_type,
    after_value, actor_id, idempotency_key
  ) values (
    task_row.family_id, task_row.student_id, task_row.subject_id, 'correction_attempt',
    attempt_id::text, 'correction_validated',
    jsonb_build_object('attempt_id', attempt_id, 'attempt_number', next_attempt_number,
      'correction_passed', correction_passed, 'redo_required', review_row.redo_required,
      'redo_passed', redo_passed), auth.uid(), target_idempotency_key
  );
  perform public.notify_task_audience(target_task_id, 'student',
    case when correction_passed then 'correction_accepted' else 'correction_retry' end,
    case when correction_passed then '订正验收完成' else '订正未通过，请继续修改' end,
    task_row.title);
  return attempt_id;
end;
$$;

create or replace function public.revoke_correction_attempt(
  target_attempt_id uuid,
  target_revoke_reason text,
  expected_version integer,
  target_idempotency_key uuid
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  attempt_row public.correction_attempts%rowtype;
  task_row public.homework_tasks%rowtype;
  workflow_row public.task_workflow_current%rowtype;
  evidence_row record;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if nullif(trim(target_revoke_reason), '') is null then raise exception 'revoke reason required'; end if;
  if target_idempotency_key is null then raise exception 'idempotency key required'; end if;
  if exists (select 1 from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key) then return; end if;
  select * into attempt_row from public.correction_attempts where id = target_attempt_id;
  select * into task_row from public.homework_tasks where id = attempt_row.task_id and deleted_at is null;
  if attempt_row.id is null or task_row.id is null or not public.is_task_tutor(task_row.id) then raise exception 'subject tutor access required'; end if;
  select * into workflow_row from public.task_workflow_current where task_id = task_row.id for update;
  if workflow_row.version <> expected_version then raise exception 'version conflict'; end if;
  if exists (select 1 from public.correction_attempt_revocations where correction_attempt_id = attempt_row.id) then raise exception 'attempt already revoked'; end if;
  insert into public.correction_attempt_revocations(correction_attempt_id, reason, revoked_by, idempotency_key)
  values(attempt_row.id, trim(target_revoke_reason), auth.uid(), target_idempotency_key);
  for evidence_row in
    select evidence.id, evidence.knowledge_node_id from public.mastery_evidence evidence
    where evidence.correction_attempt_id = attempt_row.id
      and not exists (select 1 from public.mastery_evidence_revocations revoked where revoked.evidence_id = evidence.id)
  loop
    insert into public.mastery_evidence_revocations(evidence_id, reason, revoked_by)
    values(evidence_row.id, trim(target_revoke_reason), auth.uid());
    perform public.recalculate_mastery_snapshot(evidence_row.knowledge_node_id);
  end loop;
  perform public.refresh_task_workflow(task_row.id);
  insert into public.change_events(
    family_id, student_id, subject_id, entity_type, entity_id, event_type,
    before_value, reason, actor_id, idempotency_key
  ) values (
    task_row.family_id, task_row.student_id, task_row.subject_id, 'correction_attempt',
    attempt_row.id::text, 'correction_revoked', jsonb_build_object('attempt_id', attempt_row.id),
    trim(target_revoke_reason), auth.uid(), target_idempotency_key
  );
end;
$$;

create or replace function public.confirm_knowledge_mastery(
  target_task_id uuid,
  target_knowledge_node_id uuid,
  target_level public.mastery_level,
  target_note text,
  expected_version integer,
  target_idempotency_key uuid
)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  task_row public.homework_tasks%rowtype;
  workflow_row public.task_workflow_current%rowtype;
  review_row public.task_review_records%rowtype;
  correction_row public.correction_attempts%rowtype;
  evidence_id uuid;
  current_stage public.workflow_stage;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if target_idempotency_key is null then raise exception 'idempotency key required'; end if;
  if target_level = 'unpracticed' then raise exception 'unpracticed is not a tutor assessment'; end if;
  if exists (select 1 from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key) then
    select (after_value ->> 'evidence_id')::uuid into evidence_id
    from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key;
    return evidence_id;
  end if;
  select * into task_row from public.homework_tasks where id = target_task_id and deleted_at is null;
  if task_row.id is null or not public.is_task_tutor(task_row.id) then raise exception 'subject tutor access required'; end if;
  if not exists (
    select 1 from public.task_knowledge_links
    where task_id = target_task_id and knowledge_node_id = target_knowledge_node_id
  ) then raise exception 'knowledge node is not linked to this homework version'; end if;
  select * into workflow_row from public.task_workflow_current where task_id = target_task_id for update;
  if workflow_row.version <> expected_version then raise exception 'version conflict'; end if;
  if workflow_row.stage not in ('awaiting_acceptance', 'closed_loop') then raise exception 'task is not ready for mastery assessment'; end if;
  select review.* into review_row from public.task_review_records review
  where review.task_id = target_task_id
    and not exists (select 1 from public.task_review_revocations revoked where revoked.review_id = review.id)
  order by review.review_number desc limit 1;
  if review_row.id is null then raise exception 'active review required'; end if;

  if review_row.correction_required then
    select correction.* into correction_row from public.correction_attempts correction
    where correction.review_id = review_row.id
      and not exists (select 1 from public.correction_attempt_revocations revoked where revoked.correction_attempt_id = correction.id)
    order by correction.attempt_number desc limit 1;
  end if;
  if target_level = 'mastered' and review_row.correction_required
    and (correction_row.id is null or not correction_row.correction_passed)
  then raise exception 'correction must pass before mastery'; end if;
  if target_level = 'mastered' and review_row.redo_required
    and (correction_row.id is null or not correction_row.redo_passed)
  then raise exception 'independent redo must pass before mastery'; end if;

  insert into public.mastery_evidence_revocations(evidence_id, reason, revoked_by)
  select evidence.id, '被新的家教评级取代', auth.uid()
  from public.mastery_evidence evidence
  where evidence.task_id = target_task_id
    and evidence.knowledge_node_id = target_knowledge_node_id
    and evidence.evidence_type = 'tutor_assessment'
    and not exists (
      select 1 from public.mastery_evidence_revocations revoked
      where revoked.evidence_id = evidence.id
    );

  insert into public.mastery_evidence(
    student_id, subject_id, knowledge_node_id, task_id, homework_version_id,
    review_id, correction_attempt_id, evidence_type, level, detail, created_by
  ) values (
    task_row.student_id, task_row.subject_id, target_knowledge_node_id,
    task_row.id, task_row.homework_version_id, review_row.id, correction_row.id,
    'tutor_assessment', target_level,
    jsonb_build_object('note', coalesce(target_note, '')), auth.uid()
  ) returning id into evidence_id;
  perform public.recalculate_mastery_snapshot(target_knowledge_node_id);
  current_stage := public.refresh_task_workflow(target_task_id);
  if current_stage in ('awaiting_acceptance', 'closed_loop') and not exists (
    select 1 from public.task_knowledge_links link
    where link.task_id = task_row.id
      and not exists (
        select 1 from public.mastery_evidence evidence
        where evidence.task_id = task_row.id and evidence.knowledge_node_id = link.knowledge_node_id
          and evidence.evidence_type = 'tutor_assessment' and evidence.level = 'mastered'
          and not exists (select 1 from public.mastery_evidence_revocations revoked where revoked.evidence_id = evidence.id)
      )
  ) then
    update public.task_reviews set mastery_confirmed = true, updated_at = now() where task_id = target_task_id;
  end if;
  insert into public.change_events(
    family_id, student_id, subject_id, entity_type, entity_id, event_type,
    after_value, actor_id, idempotency_key
  ) values (
    task_row.family_id, task_row.student_id, task_row.subject_id, 'mastery_evidence',
    evidence_id::text, 'mastery_assessed',
    jsonb_build_object('evidence_id', evidence_id, 'knowledge_node_id', target_knowledge_node_id, 'level', target_level),
    auth.uid(), target_idempotency_key
  );
  return evidence_id;
end;
$$;

create or replace function public.revoke_mastery_evidence(
  target_evidence_id uuid,
  target_revoke_reason text,
  expected_version integer,
  target_idempotency_key uuid
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  evidence_row public.mastery_evidence%rowtype;
  task_row public.homework_tasks%rowtype;
  workflow_row public.task_workflow_current%rowtype;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if nullif(trim(target_revoke_reason), '') is null then raise exception 'revoke reason required'; end if;
  if target_idempotency_key is null then raise exception 'idempotency key required'; end if;
  if exists (select 1 from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key) then return; end if;
  select * into evidence_row from public.mastery_evidence where id = target_evidence_id;
  select * into task_row from public.homework_tasks where id = evidence_row.task_id and deleted_at is null;
  if evidence_row.id is null or task_row.id is null or not public.is_task_tutor(task_row.id) then raise exception 'subject tutor access required'; end if;
  select * into workflow_row from public.task_workflow_current where task_id = task_row.id for update;
  if workflow_row.version <> expected_version then raise exception 'version conflict'; end if;
  if exists (select 1 from public.mastery_evidence_revocations where evidence_id = evidence_row.id) then raise exception 'evidence already revoked'; end if;
  insert into public.mastery_evidence_revocations(evidence_id, reason, revoked_by)
  values(evidence_row.id, trim(target_revoke_reason), auth.uid());
  perform public.recalculate_mastery_snapshot(evidence_row.knowledge_node_id);
  update public.task_reviews set mastery_confirmed = false, updated_at = now() where task_id = task_row.id;
  perform public.refresh_task_workflow(task_row.id);
  insert into public.change_events(
    family_id, student_id, subject_id, entity_type, entity_id, event_type,
    before_value, reason, actor_id, idempotency_key
  ) values (
    task_row.family_id, task_row.student_id, task_row.subject_id, 'mastery_evidence',
    evidence_row.id::text, 'mastery_evidence_revoked',
    jsonb_build_object('evidence_id', evidence_row.id, 'level', evidence_row.level),
    trim(target_revoke_reason), auth.uid(), target_idempotency_key
  );
end;
$$;

create or replace function public.confirm_submission_checkpoint(
  target_checkpoint_id uuid,
  target_note text,
  expected_version integer,
  target_idempotency_key uuid
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  checkpoint_row public.submission_checkpoints%rowtype;
  homework_row public.homeworks%rowtype;
  affected_task_id uuid;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if target_idempotency_key is null then raise exception 'idempotency key required'; end if;
  if exists (select 1 from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key) then return; end if;
  select * into checkpoint_row from public.submission_checkpoints where id = target_checkpoint_id for update;
  if checkpoint_row.id is null or not public.is_checkpoint_tutor(checkpoint_row.id) then raise exception 'subject tutor access required'; end if;
  if checkpoint_row.version <> expected_version then raise exception 'version conflict'; end if;
  if checkpoint_row.status = 'confirmed' then raise exception 'checkpoint already confirmed'; end if;
  select * into homework_row from public.homeworks where id = checkpoint_row.homework_id;
  update public.submission_checkpoints set
    status = 'confirmed', confirmed_by = auth.uid(), confirmed_at = now(),
    revoked_by = null, revoked_at = null, revoke_reason = null,
    note = coalesce(target_note, ''), version = version + 1
  where id = checkpoint_row.id;
  insert into public.submission_confirmations(checkpoint_id, action, note, actor_id, idempotency_key)
  values(checkpoint_row.id, 'confirmed', coalesce(target_note, ''), auth.uid(), target_idempotency_key);
  insert into public.change_events(
    family_id, student_id, subject_id, entity_type, entity_id, event_type,
    before_value, after_value, actor_id, idempotency_key
  ) values (
    homework_row.family_id, homework_row.student_id, homework_row.subject_id,
    'submission_checkpoint', checkpoint_row.id::text, 'submission_confirmed',
    jsonb_build_object('status', checkpoint_row.status),
    jsonb_build_object('status', 'confirmed', 'confirmed_at', now()),
    auth.uid(), target_idempotency_key
  );
  for affected_task_id in select id from public.homework_tasks where homework_id = homework_row.id and deleted_at is null loop
    perform public.refresh_task_workflow(affected_task_id);
    update public.task_reviews set school_submitted_at = now(), updated_at = now() where task_id = affected_task_id;
  end loop;
  if checkpoint_row.task_id is not null then
    perform public.notify_task_audience(checkpoint_row.task_id, 'parent', 'submission_confirmed', '学校平台提交已确认', checkpoint_row.label);
  end if;
end;
$$;

create or replace function public.revoke_submission_checkpoint(
  target_checkpoint_id uuid,
  target_revoke_reason text,
  expected_version integer,
  target_idempotency_key uuid
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  checkpoint_row public.submission_checkpoints%rowtype;
  homework_row public.homeworks%rowtype;
  affected_task_id uuid;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if nullif(trim(target_revoke_reason), '') is null then raise exception 'revoke reason required'; end if;
  if target_idempotency_key is null then raise exception 'idempotency key required'; end if;
  if exists (select 1 from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key) then return; end if;
  select * into checkpoint_row from public.submission_checkpoints where id = target_checkpoint_id for update;
  if checkpoint_row.id is null or not public.is_checkpoint_tutor(checkpoint_row.id) then raise exception 'subject tutor access required'; end if;
  if checkpoint_row.version <> expected_version then raise exception 'version conflict'; end if;
  if checkpoint_row.status <> 'confirmed' then raise exception 'only confirmed checkpoint can be revoked'; end if;
  select * into homework_row from public.homeworks where id = checkpoint_row.homework_id;
  update public.submission_checkpoints set
    status = 'revoked', revoked_by = auth.uid(), revoked_at = now(),
    revoke_reason = trim(target_revoke_reason), version = version + 1
  where id = checkpoint_row.id;
  insert into public.submission_confirmations(checkpoint_id, action, reason, actor_id, idempotency_key)
  values(checkpoint_row.id, 'revoked', trim(target_revoke_reason), auth.uid(), target_idempotency_key);
  insert into public.change_events(
    family_id, student_id, subject_id, entity_type, entity_id, event_type,
    before_value, after_value, reason, actor_id, idempotency_key
  ) values (
    homework_row.family_id, homework_row.student_id, homework_row.subject_id,
    'submission_checkpoint', checkpoint_row.id::text, 'submission_revoked',
    jsonb_build_object('status', checkpoint_row.status),
    jsonb_build_object('status', 'revoked'), trim(target_revoke_reason),
    auth.uid(), target_idempotency_key
  );
  for affected_task_id in select id from public.homework_tasks where homework_id = homework_row.id and deleted_at is null loop
    perform public.refresh_task_workflow(affected_task_id);
    update public.task_reviews set school_submitted_at = null, updated_at = now() where task_id = affected_task_id;
  end loop;
  if checkpoint_row.task_id is not null then
    perform public.notify_task_audience(checkpoint_row.task_id, 'parent', 'submission_revoked', '学校平台提交确认已撤销', trim(target_revoke_reason));
  end if;
end;
$$;

create or replace function public.reopen_task_workflow(
  target_task_id uuid,
  reopen_reason text,
  expected_version integer,
  target_idempotency_key uuid
)
returns void
language plpgsql security definer set search_path = public
as $$
declare
  task_row public.homework_tasks%rowtype;
  workflow_row public.task_workflow_current%rowtype;
  evidence_row record;
  node_id uuid;
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  if nullif(trim(reopen_reason), '') is null then raise exception 'reopen reason required'; end if;
  if target_idempotency_key is null then raise exception 'idempotency key required'; end if;
  if exists (select 1 from public.change_events where actor_id = auth.uid() and idempotency_key = target_idempotency_key) then return; end if;
  select * into task_row from public.homework_tasks where id = target_task_id and deleted_at is null;
  if task_row.id is null or not public.is_task_tutor(task_row.id) then raise exception 'subject tutor access required'; end if;
  select * into workflow_row from public.task_workflow_current where task_id = target_task_id for update;
  if workflow_row.version <> expected_version then raise exception 'version conflict'; end if;
  if workflow_row.stage not in ('awaiting_acceptance', 'closed_loop') then raise exception 'only accepted workflow can be reopened'; end if;

  for evidence_row in
    select evidence.id, evidence.knowledge_node_id from public.mastery_evidence evidence
    where evidence.task_id = target_task_id and evidence.evidence_type = 'tutor_assessment'
      and not exists (select 1 from public.mastery_evidence_revocations revoked where revoked.evidence_id = evidence.id)
  loop
    insert into public.mastery_evidence_revocations(evidence_id, reason, revoked_by)
    values(evidence_row.id, trim(reopen_reason), auth.uid());
    perform public.recalculate_mastery_snapshot(evidence_row.knowledge_node_id);
  end loop;
  for node_id in
    select link.knowledge_node_id from public.task_knowledge_links link
    where link.task_id = task_row.id
  loop
    insert into public.mastery_evidence(
      student_id, subject_id, knowledge_node_id, task_id, homework_version_id,
      evidence_type, level, detail, created_by
    ) values (
      task_row.student_id, task_row.subject_id, node_id, task_row.id,
      task_row.homework_version_id, 'reopen', 'reinforce',
      jsonb_build_object('reason', trim(reopen_reason)), auth.uid()
    );
    perform public.recalculate_mastery_snapshot(node_id);
  end loop;
  update public.student_task_activity set run_state = 'ready', completed_at = null, updated_at = now() where task_id = target_task_id;
  update public.task_workflow_current set active_started_at = null, last_completed_at = null where task_id = target_task_id;
  update public.task_reviews set mastery_confirmed = false, updated_at = now() where task_id = target_task_id;
  insert into public.study_session_events(task_id, student_id, event_type, actor_id, idempotency_key, payload)
  values(target_task_id, task_row.student_id, 'reopened', auth.uid(), target_idempotency_key,
    jsonb_build_object('reason', trim(reopen_reason)));
  perform public.refresh_task_workflow(target_task_id);
  insert into public.change_events(
    family_id, student_id, subject_id, entity_type, entity_id, event_type,
    before_value, after_value, reason, actor_id, idempotency_key
  ) values (
    task_row.family_id, task_row.student_id, task_row.subject_id, 'task', task_row.id::text,
    'workflow_reopened', jsonb_build_object('stage', workflow_row.stage),
    jsonb_build_object('stage', 'ready'), trim(reopen_reason), auth.uid(), target_idempotency_key
  );
  perform public.notify_task_audience(target_task_id, 'parent', 'workflow_reopened', '家教已重新打开任务', trim(reopen_reason));
  perform public.notify_task_audience(target_task_id, 'student', 'workflow_reopened', '任务已重新打开', task_row.title);
end;
$$;

create or replace function public.mark_notification_read(target_notification_id bigint, mark_as_read boolean)
returns void
language plpgsql security definer set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'authentication required'; end if;
  update public.notifications
  set read_at = case when mark_as_read then now() else null end
  where id = target_notification_id and recipient_id = auth.uid();
  if not found then raise exception 'notification not found'; end if;
end;
$$;

alter table public.plan_dependencies enable row level security;
alter table public.task_workflow_current enable row level security;
alter table public.study_session_events enable row level security;
alter table public.task_review_records enable row level security;
alter table public.task_review_revocations enable row level security;
alter table public.correction_attempts enable row level security;
alter table public.correction_attempt_revocations enable row level security;
alter table public.mastery_evidence enable row level security;
alter table public.mastery_evidence_revocations enable row level security;
alter table public.mastery_snapshots enable row level security;
alter table public.submission_confirmations enable row level security;
alter table public.notifications enable row level security;

create policy plan_dependencies_select_authorized on public.plan_dependencies
for select to authenticated using (public.can_access_task(predecessor_task_id) and public.can_access_task(successor_task_id));
create policy task_workflow_select_authorized on public.task_workflow_current
for select to authenticated using (public.can_access_task(task_id));
create policy study_session_events_select_authorized on public.study_session_events
for select to authenticated using (public.can_access_task(task_id));
create policy task_review_records_select_authorized on public.task_review_records
for select to authenticated using (public.can_access_task(task_id));
create policy task_review_revocations_select_authorized on public.task_review_revocations
for select to authenticated using (
  exists (select 1 from public.task_review_records review where review.id = task_review_revocations.review_id and public.can_access_task(review.task_id))
);
create policy correction_attempts_select_authorized on public.correction_attempts
for select to authenticated using (public.can_access_task(task_id));
create policy correction_attempt_revocations_select_authorized on public.correction_attempt_revocations
for select to authenticated using (
  exists (select 1 from public.correction_attempts attempt where attempt.id = correction_attempt_revocations.correction_attempt_id and public.can_access_task(attempt.task_id))
);
create policy mastery_evidence_select_authorized on public.mastery_evidence
for select to authenticated using (public.can_access_task(task_id));
create policy mastery_evidence_revocations_select_authorized on public.mastery_evidence_revocations
for select to authenticated using (
  exists (select 1 from public.mastery_evidence evidence where evidence.id = mastery_evidence_revocations.evidence_id and public.can_access_task(evidence.task_id))
);
create policy mastery_snapshots_select_authorized on public.mastery_snapshots
for select to authenticated using (
  public.is_student_owner(student_id)
  or exists (select 1 from public.students student where student.id = mastery_snapshots.student_id and public.is_family_parent(student.family_id))
  or public.is_subject_tutor(student_id, subject_id)
);
create policy submission_confirmations_select_authorized on public.submission_confirmations
for select to authenticated using (
  exists (select 1 from public.submission_checkpoints checkpoint where checkpoint.id = submission_confirmations.checkpoint_id and public.can_access_homework(checkpoint.homework_id))
);
create policy notifications_select_recipient on public.notifications
for select to authenticated using (recipient_id = auth.uid());

drop policy if exists homework_tasks_insert_parent on public.homework_tasks;
drop policy if exists homework_tasks_update_parent on public.homework_tasks;
drop policy if exists homework_tasks_delete_parent on public.homework_tasks;
drop policy if exists task_activity_insert_student on public.student_task_activity;
drop policy if exists task_activity_update_student on public.student_task_activity;
drop policy if exists task_reviews_insert_subject_tutor on public.task_reviews;
drop policy if exists task_reviews_update_subject_tutor on public.task_reviews;
drop policy if exists knowledge_mastery_insert_subject_tutor on public.knowledge_mastery;
drop policy if exists knowledge_mastery_update_subject_tutor on public.knowledge_mastery;

revoke insert, update, delete on public.homework_tasks from authenticated;
revoke insert, update, delete on public.student_task_activity from authenticated;
revoke insert, update, delete on public.task_reviews from authenticated;
revoke insert, update, delete on public.knowledge_mastery from authenticated;
revoke insert, update, delete on public.submission_checkpoints from authenticated;
revoke all on public.plan_dependencies from authenticated;
revoke all on public.task_workflow_current from authenticated;
revoke all on public.study_session_events from authenticated;
revoke all on public.task_review_records from authenticated;
revoke all on public.task_review_revocations from authenticated;
revoke all on public.correction_attempts from authenticated;
revoke all on public.correction_attempt_revocations from authenticated;
revoke all on public.mastery_evidence from authenticated;
revoke all on public.mastery_evidence_revocations from authenticated;
revoke all on public.mastery_snapshots from authenticated;
revoke all on public.submission_confirmations from authenticated;
revoke all on public.notifications from authenticated;

grant select on public.plan_dependencies to authenticated;
grant select on public.task_workflow_current to authenticated;
grant select on public.study_session_events to authenticated;
grant select on public.task_review_records to authenticated;
grant select on public.task_review_revocations to authenticated;
grant select on public.correction_attempts to authenticated;
grant select on public.correction_attempt_revocations to authenticated;
grant select on public.mastery_evidence to authenticated;
grant select on public.mastery_evidence_revocations to authenticated;
grant select on public.mastery_snapshots to authenticated;
grant select on public.submission_confirmations to authenticated;
grant select on public.notifications to authenticated;

revoke all on function public.move_homework_task(uuid, date, text) from authenticated;
revoke all on function public.is_task_tutor(uuid) from public;
revoke all on function public.is_checkpoint_tutor(uuid) from public;
revoke all on function public.initialize_task_workflow() from public;
revoke all on function public.notify_task_audience(uuid, text, text, text, text) from public;
revoke all on function public.recalculate_mastery_snapshot(uuid) from public;
revoke all on function public.refresh_task_workflow(uuid) from public;
revoke all on function public.record_student_task_event(uuid, text, text[], integer, uuid) from public;
revoke all on function public.move_homework_blocks(uuid, date, text, integer, boolean, uuid) from public;
revoke all on function public.append_homework_block(uuid, date, public.plan_block_type, text, uuid) from public;
revoke all on function public.split_homework_block(uuid, integer, date, text, integer, uuid) from public;
revoke all on function public.merge_homework_blocks(uuid, uuid, integer, integer, text, uuid) from public;
revoke all on function public.save_task_review(uuid, text, text[], text[], boolean, boolean, text, integer, uuid) from public;
revoke all on function public.revoke_task_review(uuid, text, integer, uuid) from public;
revoke all on function public.record_correction_attempt(uuid, boolean, boolean, text, integer, uuid) from public;
revoke all on function public.revoke_correction_attempt(uuid, text, integer, uuid) from public;
revoke all on function public.confirm_knowledge_mastery(uuid, uuid, public.mastery_level, text, integer, uuid) from public;
revoke all on function public.revoke_mastery_evidence(uuid, text, integer, uuid) from public;
revoke all on function public.confirm_submission_checkpoint(uuid, text, integer, uuid) from public;
revoke all on function public.revoke_submission_checkpoint(uuid, text, integer, uuid) from public;
revoke all on function public.reopen_task_workflow(uuid, text, integer, uuid) from public;
revoke all on function public.mark_notification_read(bigint, boolean) from public;

grant execute on function public.record_student_task_event(uuid, text, text[], integer, uuid) to authenticated;
grant execute on function public.move_homework_blocks(uuid, date, text, integer, boolean, uuid) to authenticated;
grant execute on function public.append_homework_block(uuid, date, public.plan_block_type, text, uuid) to authenticated;
grant execute on function public.split_homework_block(uuid, integer, date, text, integer, uuid) to authenticated;
grant execute on function public.merge_homework_blocks(uuid, uuid, integer, integer, text, uuid) to authenticated;
grant execute on function public.save_task_review(uuid, text, text[], text[], boolean, boolean, text, integer, uuid) to authenticated;
grant execute on function public.revoke_task_review(uuid, text, integer, uuid) to authenticated;
grant execute on function public.record_correction_attempt(uuid, boolean, boolean, text, integer, uuid) to authenticated;
grant execute on function public.revoke_correction_attempt(uuid, text, integer, uuid) to authenticated;
grant execute on function public.confirm_knowledge_mastery(uuid, uuid, public.mastery_level, text, integer, uuid) to authenticated;
grant execute on function public.revoke_mastery_evidence(uuid, text, integer, uuid) to authenticated;
grant execute on function public.confirm_submission_checkpoint(uuid, text, integer, uuid) to authenticated;
grant execute on function public.revoke_submission_checkpoint(uuid, text, integer, uuid) to authenticated;
grant execute on function public.reopen_task_workflow(uuid, text, integer, uuid) to authenticated;
grant execute on function public.mark_notification_read(bigint, boolean) to authenticated;

do $$ begin alter publication supabase_realtime add table public.task_workflow_current; exception when duplicate_object or undefined_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.study_session_events; exception when duplicate_object or undefined_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.task_review_records; exception when duplicate_object or undefined_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.correction_attempts; exception when duplicate_object or undefined_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.mastery_snapshots; exception when duplicate_object or undefined_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.submission_confirmations; exception when duplicate_object or undefined_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.notifications; exception when duplicate_object or undefined_object then null; end $$;
